# Generated by Django 4.2 on 2023-04-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('street_name', models.CharField(max_length=200)),
                ('street_number', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.province')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.address'),
            preserve_default=False,
        ),
    ]
