# Generated by Django 4.2 on 2023-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_province_address_vendorprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
