# Generated by Django 4.2 on 2023-04-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorPicture',
            new_name='VendorProfilePicture',
        ),
        migrations.RenameModel(
            old_name='PromotionPicture',
            new_name='VendorPromotionPicture',
        ),
        migrations.RenameField(
            model_name='vendorprofilepicture',
            old_name='vendor',
            new_name='vendor_profile',
        ),
        migrations.RenameField(
            model_name='vendorpromotionpicture',
            old_name='vendor',
            new_name='vendor_promotion',
        ),
    ]
