# Generated by Django 4.2 on 2023-04-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_vendorpicture_vendorprofilepicture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpromotion',
            name='category',
        ),
    ]
