# Generated by Django 4.2 on 2023-04-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_vendorpromotion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpromotion',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
