# Generated by Django 4.2 on 2023-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vendorpromotion_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofilepicture',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
