# Generated by Django 4.2 on 2023-04-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendorprofilepicture_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpromotionpicture',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
