# Generated by Django 4.2 on 2023-04-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vendorpromotionpicture_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendorcategory'),
        ),
    ]
