# Generated by Django 4.2 on 2023-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_address_unit_alter_vendorprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
