# Generated by Django 4.2 on 2023-05-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vendor_enabled_vendor_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vendor_promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendorpromotion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('public_key', models.CharField(max_length=3000)),
                ('verified', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofilepicture',
            name='vendor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='vendorpromotionpicture',
            name='vendor_promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.vendorpromotion'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('claimed_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.claimedpromotion')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
