# Generated by Django 4.2 on 2023-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_claimedpromotion_customer_alter_vendorcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='tag_value',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
